# Generated by Django 4.2.3 on 2023-08-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='portfoliouser',
            managers=[
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
